include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [lib/**.gen.dart, lib/**.gr.dart, lib/**.g.dart, lib/**.freezed.dart, lib/**.hive.dart]
  errors:
    invalid_annotation_target: ignore

linter:
  rules: