name: fox_fit_schedule
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.1
  intl: ^0.18.0
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.0
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  json_serializable: ^6.3.1
  flutter_dotenv: ^5.0.2
  logger: ^1.1.0
  dartz: ^0.10.1
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  flutter_svg: ^1.1.1+1
  get_it: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^4.0.3
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/schedule/common/icons/
    - lib/schedule/config/

flutter_gen:
  output: lib/schedule/common/gen
